### ISSUE TITLE
Select Python Environment Warning

### ISSUE THREAD

**Issue by dalegebit** [OhYee/WSLenv#1]
It looks like vscode cannot recognize the generated python.exe. Any solution or explanation to this?

**Comment by OhYee** [comment]
@dalegebit 
Have you set the PATH system variable?
After set the PATH, you have to restart cmd.

And if you have installed Python in Windows, VSCode will use the first `python.exe` in the PATH(if you use the `python.exe` as generated filename).

Also, you can change `python.pythonPath": "python` in the `setting.json`.
Such as `"python.pythonPath": "C:\\env\\python.exe"`

**Comment by dalegebit** [comment]
Yes, I have default python installed in windows, but I have set up `python.pythonPath` in `setting.json` and it looks like vscode simply ignores it and still asks me to set up a python interpreter.
![image](https://user-images.githubusercontent.com/9109634/53271379-1fa53280-36a3-11e9-89c7-fb13578021db.png)

**Comment by OhYee** [comment]
I guess the reason for this is because VSCode recognizes that Python does not simply recognize the EXE, but does some other operations to determine the version, etc. The Windows version of VSCode does not correctly recognize Python in WSL, although he can normal use.

Future versions of VSCode may have better support for WSL. You can just use this tool for simple work.
(If you don't use the debug tools, it works well. )

**Comment by dalegebit** [comment]
Well, thank you anyway!
